name: "C-1. 동기화 구글드라이브 파일 가져오기"

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl google-api-python-client google-auth gspread

    - name: Execute Python automation script
      env:
        GOOGLE_JSON_RAW: ${{ secrets.GOOGLE_JSON_RAW }}
        TARGET_SPREADSHEET_ID: ${{ secrets.TARGET_SPREADSHEET_ID }}
      run: python sync_data.py
